language: elixir
elixir:
  - 1.8
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix compile
  # - mix test
  # - mix cover
after_success:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch
after_failure:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch
cache:
  directories:
    - _build
    - deps
